export function initJournalEditor(ui) {
  const { $, supabase, registerForm, showEditorForm, showEditorList, verifyDelete } = ui;
  const form = $('journal-form');
  const list = $('journal-entry-list');
  const message = $('journal-form-message');
  const body = form.elements.body;
  const title = form.elements.title;
  const slug = form.elements.slug;
  const preview = $('journal-body-preview');
  let loadVersion = 0;
  let lastGeneratedSlug = '';

  registerForm(form, list.closest('.editor-list-wrap'));
  $('new-journal-entry').addEventListener('click', () => {
    form.reset();
    form.elements.id.value = '';
    slug.dataset.autoGenerated = 'true';
    lastGeneratedSlug = '';
    message.textContent = '';
    renderPreview();
    showEditorForm(form);
  });
  title.addEventListener('input', () => {
    if (slug.dataset.autoGenerated === 'false') return;
    const nextSlug = slugify(title.value);
    slug.value = nextSlug;
    lastGeneratedSlug = nextSlug;
  });
  slug.addEventListener('input', () => {
    slug.dataset.autoGenerated = !slug.value || slug.value === lastGeneratedSlug || slug.value === slugify(title.value)
      ? 'true'
      : 'false';
  });
  body.addEventListener('input', renderPreview);
  form.addEventListener('submit', saveJournalEntry);
  renderPreview();

  async function saveJournalEntry(event) {
    event.preventDefault();
    message.textContent = 'saving...';
    const values = new FormData(form);
    const payload = {
      title: values.get('title'),
      slug: slugify(values.get('slug')),
      body: { markdown: values.get('body') || '' },
      status: values.get('status'),
      published_at: values.get('status') === 'published' ? new Date().toISOString() : null
    };
    const id = values.get('id');
    const query = id
      ? supabase.client.from('journal_entries').update(payload).eq('id', id)
      : supabase.client.from('journal_entries').insert(payload);
    const { error } = await query;
    message.textContent = error ? error.message : 'saved.';
    if (error) return;
    form.reset();
    form.elements.id.value = '';
    slug.dataset.autoGenerated = 'true';
    lastGeneratedSlug = '';
    renderPreview();
    showEditorList(form);
    loadJournalEntries();
  }

  function renderPreview() {
    const source = body.value;
    if (!source.trim()) {
      preview.replaceChildren(Object.assign(document.createElement('p'), { className: 'admin-help', textContent: 'Your formatted entry appears here.' }));
      return;
    }
    const escaped = ui.escapeHtml(source).replace(/\n/g, '<br>');
    const rendered = window.marked?.parse ? window.marked.parse(source) : `<p>${escaped}</p>`;
    preview.innerHTML = window.DOMPurify?.sanitize ? window.DOMPurify.sanitize(rendered) : `<p>${escaped}</p>`;
  }

  async function loadJournalEntries() {
    const version = ++loadVersion;
    const { data, error } = await supabase.client.from('journal_entries')
      .select('id,title,slug,status,updated_at').order('updated_at', { ascending: false });
    if (version !== loadVersion) return;
    if (error) { list.textContent = error.message; return; }
    if (!data?.length) { list.textContent = 'No entries yet. Start with the form above.'; return; }
    list.replaceChildren(...data.map((entry) => {
      const item = document.createElement('div'); item.className = 'editor-list-item';
      const details = document.createElement('button'); details.className = 'editor-row-main'; details.type = 'button';
      const title = document.createElement('strong'); title.textContent = entry.title;
      const meta = document.createElement('small'); meta.textContent = `${entry.status} · ${entry.slug}`;
      details.append(title, meta); details.addEventListener('click', () => fillJournalForm(entry.id));
      const remove = document.createElement('button'); remove.className = 'btn btn-danger'; remove.type = 'button'; remove.textContent = 'delete';
      remove.addEventListener('click', () => deleteJournalEntry(entry.id, entry.title));
      const actions = document.createElement('div'); actions.className = 'editor-item-actions'; actions.append(remove);
      item.append(details, actions);
      return item;
    }));
  }

  async function deleteJournalEntry(id, title) {
    if (!await verifyDelete(title, message)) return;
    message.textContent = 'deleting...';
    const { error } = await supabase.client.from('journal_entries').delete().eq('id', id);
    message.textContent = error ? error.message : 'Entry deleted.';
    if (error) return;
    form.reset();
    form.elements.id.value = '';
    showEditorList(form);
    loadJournalEntries();
  }

  async function fillJournalForm(id) {
    const { data, error } = await supabase.client.from('journal_entries').select('*').eq('id', id).single();
    if (error) { message.textContent = error.message; return; }
    form.elements.id.value = data.id;
    form.elements.title.value = data.title;
    form.elements.slug.value = data.slug;
    lastGeneratedSlug = slugify(data.title);
    slug.dataset.autoGenerated = data.slug === lastGeneratedSlug ? 'true' : 'false';
    body.value = data.body?.markdown ?? data.body?.html ?? '';
    renderPreview();
    form.elements.status.value = data.status;
    message.textContent = `editing ${data.title}`;
    showEditorForm(form);
  }

  ui.onDraftRestore((restoredForm) => {
    if (restoredForm !== form) return;
    lastGeneratedSlug = slugify(title.value);
    slug.dataset.autoGenerated = slug.value === lastGeneratedSlug ? 'true' : 'false';
    renderPreview();
  });
  return { loaders: { 'journal-editor': loadJournalEntries } };
}

function slugify(value) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
