export function initMemoriesEditor(ui) {
  const { $, supabase, registerForm, showEditorForm, showEditorList, refreshMarkdownPreviews, verifyDelete, wordCount, uploadImage } = ui;
  const memoryForm = $('memory-form');
  const memoryTitle = memoryForm.elements.title;
  const memorySlug = memoryForm.elements.slug;
  const memoryList = $('memory-list-admin');
  const photoFields = $('memory-photo-fields');
  const memoryMessage = $('memory-form-message');
  const timelineForm = $('timeline-form');
  const timelineList = $('timeline-list-admin');
  const timelineMessage = $('timeline-form-message');
  const timelineYearSelect = timelineForm.elements.calendar_year;
  populateTimelineYears(timelineYearSelect);
  let lastGeneratedSlug = '';

  registerForm(memoryForm, memoryList.closest('.editor-list-wrap'), {
    captureExtra: () => [...photoFields.querySelectorAll('.memory-photo-field')]
      .map((field) => ({ image_url: field.querySelector('[name="photo_url"]').value })),
    restoreExtra: (photos) => {
      photoFields.replaceChildren();
      (photos?.length ? photos : [{}]).forEach(addPhotoField);
    }
  });
  registerForm(timelineForm, timelineList.closest('.editor-list-wrap'));

  $('new-memory').addEventListener('click', () => {
    memoryForm.reset();
    memoryForm.elements.id.value = '';
    memorySlug.dataset.autoGenerated = 'true';
    lastGeneratedSlug = '';
    photoFields.replaceChildren();
    addPhotoField();
    updateFileName(memoryForm.elements.cover_file);
    memoryMessage.textContent = '';
    showEditorForm(memoryForm);
  });
  memoryTitle.addEventListener('input', () => {
    if (memorySlug.dataset.autoGenerated === 'false') return;
    const nextSlug = slugify(memoryTitle.value);
    memorySlug.value = nextSlug;
    lastGeneratedSlug = nextSlug;
  });
  memorySlug.addEventListener('input', () => {
    memorySlug.dataset.autoGenerated = !memorySlug.value || memorySlug.value === lastGeneratedSlug || memorySlug.value === slugify(memoryTitle.value)
      ? 'true'
      : 'false';
  });
  setupImagePicker(memoryForm.querySelector('[data-memory-file-picker]'), memoryForm.elements.cover_file);
  $('add-memory-photo').addEventListener('click', () => addPhotoField());
  memoryForm.addEventListener('submit', saveMemory);
  $('new-timeline-event').addEventListener('click', () => {
    timelineForm.reset();
    timelineForm.elements.id.value = '';
    timelineMessage.textContent = '';
    showEditorForm(timelineForm);
  });
  timelineForm.addEventListener('submit', saveTimelineEvent);

  function addPhotoField(photo = {}) {
    const field = document.createElement('div');
    field.className = 'memory-photo-field';
    const urlLabel = document.createElement('label');
    urlLabel.textContent = 'Photo URL';
    const urlInput = document.createElement('input');
    urlInput.type = 'url';
    urlInput.name = 'photo_url';
    urlInput.value = photo.image_url || '';
    urlInput.placeholder = 'https://...';
    urlLabel.appendChild(urlInput);

    const dropzone = document.createElement('div');
    dropzone.className = 'memory-upload-field';
    dropzone.dataset.memoryFilePicker = '';
    const fileInput = document.createElement('input');
    fileInput.className = 'memory-file-input';
    fileInput.type = 'file';
    fileInput.name = 'photo_file';
    fileInput.accept = 'image/*';
    fileInput.id = `memory-photo-file-${crypto.randomUUID()}`;
    const uploadLabel = document.createElement('label');
    uploadLabel.className = 'memory-upload-trigger';
    uploadLabel.htmlFor = fileInput.id;
    const icon = document.createElement('span');
    icon.className = 'memory-upload-icon';
    icon.setAttribute('aria-hidden', 'true');
    icon.textContent = '↑';
    const copy = document.createElement('span');
    copy.className = 'memory-upload-copy';
    const heading = document.createElement('strong');
    heading.textContent = 'Choose photo';
    const hint = document.createElement('small');
    hint.textContent = 'JPEG, PNG, WebP';
    copy.append(heading, hint);
    uploadLabel.append(icon, copy);
    const fileName = document.createElement('p');
    fileName.className = 'memory-file-name';
    fileName.dataset.memoryFileName = '';
    fileName.setAttribute('aria-live', 'polite');
    fileName.textContent = 'No file selected';
    dropzone.append(fileInput, uploadLabel, fileName);

    const remove = document.createElement('button');
    remove.className = 'btn btn-danger remove-photo';
    remove.type = 'button';
    remove.textContent = 'remove photo';
    field.append(urlLabel, dropzone, remove);
    field.querySelector('.remove-photo').addEventListener('click', () => field.remove());
    setupImagePicker(dropzone, fileInput);
    photoFields.appendChild(field);
  }

  async function saveMemory(event) {
    event.preventDefault();
    memoryMessage.textContent = 'saving...';
    const values = new FormData(memoryForm);
    const description = String(values.get('description') || '').trim();
    if (wordCount(description) > 100) { memoryMessage.textContent = 'Memory description must be 100 words or fewer.'; return; }

    let coverImage = values.get('cover_image') || null;
    try {
      const coverFile = memoryForm.elements.cover_file.files[0];
      if (coverFile) {
        memoryMessage.textContent = 'optimizing and uploading main image…';
        coverImage = await uploadImage(await optimizeImage(coverFile), 'covers');
      }
    } catch (error) { memoryMessage.textContent = error.message; return; }

    const stagedPhotos = [];
    for (const [index, field] of [...photoFields.querySelectorAll('.memory-photo-field')].entries()) {
      const file = field.querySelector('[name="photo_file"]').files[0];
      let imageUrl = field.querySelector('[name="photo_url"]').value.trim();
      if (!file && !imageUrl) continue;
      try {
        if (file) {
          memoryMessage.textContent = `optimizing and uploading photo ${index + 1}…`;
          imageUrl = await uploadImage(await optimizeImage(file), 'photos');
        }
      } catch (uploadError) { memoryMessage.textContent = uploadError.message; return; }
      stagedPhotos.push({ image_url: imageUrl, sort_order: index });
    }

    const payload = { title: values.get('title'), slug: values.get('slug'), description, cover_image: coverImage, status: values.get('status') };
    const id = values.get('id');
    const query = id
      ? supabase.client.from('memories').update(payload).eq('id', id).select('id').single()
      : supabase.client.from('memories').insert(payload).select('id').single();
    const { data, error } = await query;
    if (error) { memoryMessage.textContent = error.message; return; }

    const memoryId = data.id;
    const { error: removeError } = await supabase.client.from('memory_photos').delete().eq('memory_id', memoryId);
    if (removeError) { memoryMessage.textContent = removeError.message; return; }
    const photos = stagedPhotos.map((photo) => ({ ...photo, memory_id: memoryId }));
    if (photos.length) {
      const { error: photoError } = await supabase.client.from('memory_photos').insert(photos);
      if (photoError) { memoryMessage.textContent = photoError.message; return; }
    }
    memoryForm.elements.id.value = memoryId;
    memoryMessage.textContent = 'memory saved.';
    showEditorList(memoryForm);
    loadMemories();
  }

  async function saveTimelineEvent(event) {
    event.preventDefault();
    timelineMessage.textContent = 'saving...';
    const values = new FormData(timelineForm);
    const description = String(values.get('description') || '').trim();
    if (wordCount(description) > 40) { timelineMessage.textContent = 'Initial timeline description must be 40 words or fewer.'; return; }
    const dateLabel = formatTimelineMonthYear(values.get('month'), values.get('calendar_year'));
    if (!dateLabel) { timelineMessage.textContent = 'Choose a valid month and year.'; return; }
    const payload = {
      date_label: dateLabel, title: values.get('title'), description,
      more_description: values.get('more_description') || '', status: values.get('status')
    };
    const id = values.get('id');
    const query = id
      ? supabase.client.from('memory_timeline').update(payload).eq('id', id)
      : supabase.client.from('memory_timeline').insert(payload);
    const { error } = await query;
    timelineMessage.textContent = error ? error.message : 'event saved.';
    if (!error) { showEditorList(timelineForm); loadTimelineEvents(); }
  }

  async function loadMemories() {
    const { data, error } = await supabase.client.from('memories')
      .select('id,title,slug,status,updated_at').order('updated_at', { ascending: false });
    renderList(memoryList, data, error, 'No memories yet.', fillMemory, deleteMemory);
  }

  async function loadTimelineEvents() {
    const { data, error } = await supabase.client.from('memory_timeline')
      .select('id,date_label,title,status,updated_at');
    if (!error && data) data.sort((a, b) => timelineDateValue(a.date_label) - timelineDateValue(b.date_label));
    const count = document.querySelector('[data-timeline-count="memories"]');
    if (count) count.textContent = data?.length || 0;
    renderList(timelineList, data, error, 'No timeline events yet.', fillTimelineEvent, deleteTimelineEvent);
  }

  function renderList(container, data, error, emptyMessage, edit, remove) {
    container.replaceChildren();
    if (error) { container.textContent = error.message; return; }
    if (!data?.length) { container.textContent = emptyMessage; return; }
    data.forEach((entry) => {
      const item = document.createElement('div'); item.className = 'editor-list-item';
      const details = document.createElement('button'); details.className = 'editor-row-main'; details.type = 'button';
      const title = document.createElement('strong'); title.textContent = entry.title;
      const meta = document.createElement('small'); meta.textContent = `${entry.status} · ${entry.slug || entry.date_label}`;
      details.append(title, meta); details.addEventListener('click', () => edit(entry.id));
      const removeButton = document.createElement('button'); removeButton.className = 'btn btn-danger'; removeButton.type = 'button'; removeButton.textContent = 'delete';
      removeButton.addEventListener('click', () => remove(entry.id, entry.title));
      const actions = document.createElement('div'); actions.className = 'editor-item-actions'; actions.append(removeButton);
      item.append(details, actions); container.append(item);
    });
  }

  async function fillMemory(id) {
    const { data, error } = await supabase.client.from('memories').select('*,memory_photos(*)').eq('id', id).single();
    if (error) { memoryMessage.textContent = error.message; return; }
    memoryForm.elements.id.value = data.id;
    memoryForm.elements.title.value = data.title;
    memoryForm.elements.slug.value = data.slug;
    lastGeneratedSlug = slugify(data.title);
    memorySlug.dataset.autoGenerated = data.slug === lastGeneratedSlug ? 'true' : 'false';
    memoryForm.elements.description.value = data.description;
    memoryForm.elements.cover_image.value = data.cover_image || '';
    updateFileName(memoryForm.elements.cover_file);
    memoryForm.elements.status.value = data.status;
    refreshMarkdownPreviews(memoryForm);
    photoFields.replaceChildren();
    (data.memory_photos || []).sort((a, b) => a.sort_order - b.sort_order).forEach(addPhotoField);
    if (!data.memory_photos?.length) addPhotoField();
    memoryMessage.textContent = `editing ${data.title}`;
    showEditorForm(memoryForm);
  }

  function setupImagePicker(container, input) {
    if (!container || !input) return;
    const updateName = () => updateFileName(input);
    input.addEventListener('change', updateName);
  }

  function updateFileName(input) {
    const name = input?.closest('[data-memory-file-picker]')?.querySelector('[data-memory-file-name]');
    if (!name) return;
    name.textContent = input.files?.[0]?.name || 'No file selected';
  }

  async function optimizeImage(file) {
    if (!file.type.startsWith('image/')) throw new Error('Choose a valid image file.');
    let decoded;
    try {
      if (typeof createImageBitmap === 'function') {
        const bitmap = await createImageBitmap(file, { imageOrientation: 'from-image' });
        decoded = { source: bitmap, width: bitmap.width, height: bitmap.height, close: () => bitmap.close() };
      } else {
        const objectUrl = URL.createObjectURL(file);
        let image;
        try {
          image = await new Promise((resolve, reject) => {
            const element = new Image();
            element.onload = () => resolve(element);
            element.onerror = () => reject(new Error('This image could not be opened.'));
            element.src = objectUrl;
          });
        } catch (error) {
          URL.revokeObjectURL(objectUrl);
          throw error;
        }
        decoded = { source: image, width: image.naturalWidth, height: image.naturalHeight, close: () => URL.revokeObjectURL(objectUrl) };
      }
      const maxEdge = 1440;
      const scale = Math.min(1, maxEdge / decoded.width, maxEdge / decoded.height);
      const canvas = document.createElement('canvas');
      canvas.width = Math.max(1, Math.round(decoded.width * scale));
      canvas.height = Math.max(1, Math.round(decoded.height * scale));
      const context = canvas.getContext('2d', { alpha: true });
      if (!context) throw new Error('This browser could not prepare the image for upload.');
      context.drawImage(decoded.source, 0, 0, canvas.width, canvas.height);
      let blob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/webp', 0.8));
      if (!blob) throw new Error('This browser could not prepare the image for upload.');
      if (blob.size > 700 * 1024) {
        const smallerBlob = await new Promise((resolve) => canvas.toBlob(resolve, 'image/webp', 0.74));
        if (smallerBlob && smallerBlob.size < blob.size) {
          blob = smallerBlob;
        }
      }
      if (blob.size >= file.size) return file;
      const baseName = file.name.replace(/\.[^.]+$/, '') || 'memory-image';
      const extension = blob.type === 'image/webp' ? 'webp' : blob.type === 'image/jpeg' ? 'jpg' : 'png';
      return new File([blob], `${baseName}.${extension}`, { type: blob.type, lastModified: Date.now() });
    } catch (error) {
      console.warn('Could not optimize memory image; uploading the original.', error);
      return file;
    } finally {
      decoded?.close();
    }
  }

  async function fillTimelineEvent(id) {
    const { data, error } = await supabase.client.from('memory_timeline').select('*').eq('id', id).single();
    if (error) { timelineMessage.textContent = error.message; return; }
    timelineForm.elements.id.value = data.id;
    const date = parseTimelineMonthYear(data.date_label);
    timelineForm.elements.month.value = date.month;
    selectTimelineYear(timelineYearSelect, date.year);
    timelineForm.elements.title.value = data.title;
    timelineForm.elements.description.value = data.description;
    timelineForm.elements.more_description.value = data.more_description || '';
    timelineForm.elements.status.value = data.status;
    refreshMarkdownPreviews(timelineForm);
    timelineMessage.textContent = `editing ${data.title}`;
    showEditorForm(timelineForm);
  }

  async function deleteMemory(id, title) {
    if (!await verifyDelete(title, memoryMessage)) return;
    const { error } = await supabase.client.from('memories').delete().eq('id', id);
    memoryMessage.textContent = error ? error.message : 'memory deleted.';
    if (!error) loadMemories();
  }

  async function deleteTimelineEvent(id, title) {
    if (!await verifyDelete(title, timelineMessage)) return;
    const { error } = await supabase.client.from('memory_timeline').delete().eq('id', id);
    timelineMessage.textContent = error ? error.message : 'event deleted.';
    if (!error) loadTimelineEvents();
  }

  ui.onDraftRestore((restoredForm) => {
    if (restoredForm !== memoryForm) return;
    lastGeneratedSlug = slugify(memoryTitle.value);
    memorySlug.dataset.autoGenerated = memorySlug.value === lastGeneratedSlug ? 'true' : 'false';
    updateFileName(memoryForm.elements.cover_file);
  });

  return { loaders: { 'memory-editor': loadMemories, 'timeline-editor': loadTimelineEvents } };
}

function slugify(value) {
  return String(value ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

const TIMELINE_MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];

function populateTimelineYears(select) {
  const currentYear = new Date().getFullYear();
  select.replaceChildren(new Option('Choose year', ''));
  for (let year = currentYear + 5; year >= 1900; year -= 1) select.add(new Option(String(year), String(year)));
}

function selectTimelineYear(select, year) {
  if (year && !Array.from(select.options).some((option) => option.value === year)) select.add(new Option(year, year));
  select.value = year;
}

function formatTimelineMonthYear(monthValue, yearValue) {
  const month = Number(monthValue);
  const year = String(yearValue || '');
  return Number.isInteger(month) && month >= 1 && month <= 12 && /^\d{4}$/.test(year)
    ? `${TIMELINE_MONTHS[month - 1]} ${year}`
    : '';
}

function parseTimelineMonthYear(value) {
  const match = /^(January|February|March|April|May|June|July|August|September|October|November|December)\s+(\d{4})$/i.exec(String(value || '').trim());
  if (!match) return { month: '', year: '' };
  const month = TIMELINE_MONTHS.findIndex((name) => name.toLowerCase() === match[1].toLowerCase()) + 1;
  return { month: String(month), year: match[2] };
}

function timelineDateValue(value) {
  const { month, year } = parseTimelineMonthYear(value);
  return month && year ? Number(year) * 12 + Number(month) : Number.POSITIVE_INFINITY;
}
